version: '3'
services: 
  node:
    build:
      context: .
      dockerfile: node.dockerfile
    ports: 
      - "3001:3001"    
    depends_on:
      - postgres
    networks: 
      - apinetwork      
    volumes:
      - ./:/usr/src/app  
      - /usr/src/app/node_modules
  postgres:
    image: postgres
    restart: always
    ports: 
      - "11543:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD} 
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    networks: 
      - apinetwork    
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  apinetwork:
    driver: bridge
volumes:
  pgdata: