version: '3.4'

services: 
  db:
    image: postgres 
     
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD} 
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    networks: 
      - apiplacement
  node:
    build:
      context: .
      dockerfile: node.dockerfile
    ports: 
      - "3001:3001"
    depends_on: 
      - db
    networks: 
      - apiplacement      
    volumes:
        - ./:/usr/src/app
networks: 
  apiplacement:
    driver: bridge